version: '3.9'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: api-rest-prueba
    links:
      - mongo
    depends_on:
      - mongo
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 1
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db